### ISSUE TITLE
Gruppen-Links im Footer

### ISSUE THREAD

**Issue by carlobeltrame** [gloggi/abteilungs-homepage#2]
Sollten direkt Gruppen-Lightbox öffnen

**Comment by tobifra** [comment]
Da jetzt jede Gruppe einen eigenen Link hat, wird im Footer auf den Link der Lightbox verwiesen. Dies Funktioniert aber nur, wenn die in den Einstellungen ausgewählte Seite einen Content mit whoweare_show == true hat.
