### ISSUE TITLE
Reproduzierbare Links zu geöffneten Lightboxes

### ISSUE THREAD

**Issue by carlobeltrame** [gloggi/abteilungs-homepage#3]
Z.b. /agenda/?gruppe=bibergruppe-1#agenda-entry-630 sollte direkt die Gruppe auswählen und die Event-Lightbox öffnen

**Comment by tobifra** [comment]
Sollte jetzt möglich sein mit /*aktuelle Seite*/gruppe/*Gruppenname*/event/*event id*
Dies funktioniert ebenfalls nur, falls die aktuelle Seite einene Content mit whoweare_show= true hat.
Abstände im Gruppennamen werden durch Bindestriche ersetzt.

**Comment by carlobeltrame** [comment]
Cool! Ein paar Anmerkungen zur Implementation:
* Entfernen der Leerzeichen ist schon mal gut, aber es gibt noch viele andere Fälle die man abhandeln könnte. Typischerweise verwendet man dafür eine Library wie [slugify](https://www.npmjs.com/package/slugify). Diese habe ich sogar schon [im Footer verwendet](https://github.com/gloggi/abteilungs-homepage/blob/1d54f57cc27e3996e1ad26d942e2d70c998e9f05/frontend/src/components/Footer.vue#L53) um den Hash in den Gruppen-Links zu berechnen.
* Anstatt die `$route` zu watchen hat der Vue Router sogenannte [Navigation Guards](https://router.vuejs.org/guide/advanced/navigation-guards.html#in-component-guards) die aufgerufen werden wenn die Route sich ändert. Diese funktionieren aber nur auf der Route-Komponente, also auf `Page`. Man könnte diese Information dann via props an `Agenda`, `LightboxAgenda` und `GroupsContainer` weitergeben. Wenn dir das zu mühsam erscheint würde ich wenigstens die duplizierte Logik in eine Methode auslagern.
* Die Zeile https://github.com/gloggi/abteilungs-homepage/commit/1d54f57cc27e3996e1ad26d942e2d70c998e9f05#diff-d1f8af0d8cb8f4d7a38274c21410c493R111 wäre ein super Kandidat für `.some(content => content.whoweare_show)` anstatt `.filter(content=>content.whoweare_show===true).length > 0`
